# Generated by Django 4.2.6 on 2023-11-25 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cs3300_project', '0002_rename_user_player_rename_user_clip_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clip',
            name='player',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cs3300_project.player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
